apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        {{- $svcEnabled := .Values.svc.enabled | default false }}
        {{- $svcPort := .Values.svc.port | default 80 }}
        {{- if $svcEnabled }}
        ports:
        - containerPort: {{ $svcPort }}
        {{- if eq (int $svcPort) 80 }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ $svcPort }}
        {{- end }}
        {{- end }}
