{{- if .Values.svc.enabled | default "false"}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{.Values.name}}
  name: {{.Values.name}}
spec:
  type: {{ .Values.svc.type | default "ClusterIP" }}
  ports:
  - port: {{ .Values.svc.port | default 80 }}
  selector:
    app: {{.Values.name}}
{{- end }}
